name: example
description: Implementation of SECP256K1 and SECP256R1.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sec:
    path: ../
  pointycastle: ^4.0.0
  convert: ^3.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
