name: sec
description: Implementation of Standards for Efficient Cryptography (SEC) including SECP256K1 and SECP256R1.
version: 1.0.0
repository: https://github.com/xclud/dart_sec

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pointycastle: ^3.6.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
  convert: ^3.1.1
